DROP TABLE IF EXISTS TBL_RESTAURANT;

CREATE TABLE TBL_RESTAURANT (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  RESTAURANT_NAME VARCHAR(250) NOT NULL,
  RESTAURANT_ADDRESS VARCHAR(500) NOT NULL,
  ADDED_BY VARCHAR(250) NOT NULL,
  SESSION_ID INT NOT NULL,
  CREATED_DATE DATE DEFAULT NULL
);

DROP TABLE IF EXISTS TBL_SESSION;

CREATE TABLE TBL_SESSION (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  CREATED_BY VARCHAR(250) NOT NULL,
  START_DATE_TIME TIMESTAMP NOT NULL,
  END_DATE_TIME TIMESTAMP DEFAULT NULL,
  SESSION_STATUS VARCHAR(250) NOT NULL,
  SELECTED_RESTAURANT INT DEFAULT NULL
);

DROP TABLE IF EXISTS TBL_SESSION_USER;

CREATE TABLE TBL_SESSION_USER (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  USER_EMAIL_ADDRESS VARCHAR(250) NOT NULL,
  SESSION_ID INT NOT NULL
);

DROP TABLE IF EXISTS TBL_USER;

CREATE TABLE TBL_USER (
  EMAIL_ADDRESS VARCHAR(250) PRIMARY KEY,
  FIRST_NAME VARCHAR(250) NOT NULL,
  LAST_NAME VARCHAR(250) NOT NULL,
  USER_STATUS VARCHAR(250) NOT NULL,
  CREATED_DATE DATE DEFAULT NULL
);
